projectTitle: "RNAP_project"
root: /mnt/gluster01/lgbm/Larissa.Souza/PSI/DROP/RNAP_analyses-2/Output_RNAP-123
htmlOutputPath: /mnt/gluster01/lgbm/Larissa.Souza/PSI/DROP/RNAP_analyses-2/Output_RNAP-123/html
indexWithFolderName: true

hpoFile: null  # if null, downloads it from webserver
sampleAnnotation: /mnt/gluster01/lgbm/Larissa.Souza/PSI/DROP/RNAP_analyses-2/Sample-annotation-RNAP123-VUS.tsv

geneAnnotation:
    v46: /mnt/gluster01/lgbm/Larissa.Souza/anotacoes_homo_sapiens/gencode.v46.primary_assembly.annotation.gtf
genomeAssembly: hg38
genome:
    ensembl: /mnt/gluster01/lbcb/reference/grch38/Homo_sapiens.GRCh38.dna.primary_assembly.ordered.fa # path to reference genome sequence in fasta format.
    # You can define multiple reference genomes in yaml format, ncbi: path/to/ncbi, ucsc: path/to/ucsc
    # the keywords that define the path should be in the GENOME column of the sample annotation table

random_seed: true  # just for demo data, remove for analysis

exportCounts:
    # specify which gene annotations to include and which
    # groups to exclude when exporting counts
    geneAnnotations:
        - v46
    excludeGroups:
        - null    

aberrantExpression:
    run: false
    groups:
        - group1
        - group2
    fpkmCutoff: 1
    implementation: autoencoder
    padjCutoff: 0.05
    zScoreCutoff: 0
    genesToTest: null
    maxTestedDimensionProportion: 3
    yieldSize: 2000000

aberrantSplicing:
    run: true
    groups:
        - batch-vus
    recount: false
    longRead: false
    keepNonStandardChrs: false
    filter: true
    minExpressionInOneSample: 20
    quantileMinExpression: 10
    minDeltaPsi: 0.05
    implementation: PCA
    padjCutoff: 0.1
    maxTestedDimensionProportion: 6
    genesToTest: /mnt/gluster01/lgbm/Larissa.Souza/PSI/DROP/RNAP_analyses-2/27genes.yaml
    ### FRASER1 configuration
    #FRASER_version: "FRASER" 
    #deltaPsiCutoff : 0.3 
    #quantileForFiltering: 0.95 
    ### For FRASER2, use the follwing parameters instead of the 3 lines above:
    FRASER_version: "FRASER2"
    deltaPsiCutoff : 0.1
    quantileForFiltering: 0.01 

mae:
    run: false
    groups:
        - group1
        - group2
        - group3
    gatkIgnoreHeaderCheck: true
    padjCutoff: 0.05
    allelicRatioCutoff: 0.8
    addAF: true
    maxAF: 0.001
    maxVarFreqCohort: 0.05
    # VCF-BAM matching
    qcVcf: Data/qc_vcf_1000G.vcf.gz
    qcGroups:
      - mae
    dnaRnaMatchCutoff: 0.85

rnaVariantCalling:
    run: false
    groups:
        - batch_0
    highQualityVCFs:
        - Data/Mills_and_1000G_gold_standard.indels.hg19.sites.chrPrefix.vcf.gz
        - Data/1000G_phase1.snps.high_confidence.hg19.sites.chrPrefix.vcf.gz
    dbSNP: Data/00-All.vcf.gz
    repeat_mask: Data/hg19_repeatMasker_sorted.chrPrefix.bed
    createSingleVCF: true
    addAF: true
    maxAF: 0.001
    maxVarFreqCohort: 0.05
    hcArgs: ""
    minAlt: 3
    yieldSize: 100000

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools
